---
title: "Unionizing"
---

- [NewsGuild: Organize with us](https://newsguild.org/organize-with-us/)
 
- [Communication Workers of America: How to organize](https://cwa-union.org/join-union/how-organize)
 
- [SAG-AFTRA steps to join](https://www.sagaftra.org/membership-benefits/steps-join)

- [The Writers Guild of America East "contact an organizer" form](https://www.wgaeast.org/organize/contact-an-organizer/)
 
- [SPJ Florida webinar: So your newsroom wants to unionize. Now what?](https://www.youtube.com/watch?v=sX2N8CPsXBk&list=PL3LHyxW1_DWOffWquor11FndaQvaFM-3Z&index=3)
 
- [Labor Notes](https://labornotes.org/) is a good place to keep up with labor news in general, but it's also a network of members, union leaders and labor activists who can be helpful during your organization process

- Nieman Journalism Lab: [How we unionized the digital team at The Seattle Times (and how you can do it at your company too) ](https://www.niemanlab.org/2021/05/how-we-unionized-the-digital-team-at-the-seattle-times-and-how-you-can-do-it-at-your-company-too/)
 
- [AFL-CIO "form a union" page](https://aflcio.org/formaunion)
 
- [UE's five basic steps to organizing a union](https://www.ueunion.org/org_steps.html)
 
> Note about AFL-CIO and UE: while we can't organize under either of these names, the organizations have long and strong histories of successfully unionizing that we can learn from.